# Generated by Django 5.2 on 2025-04-13 19:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NewsArticle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField(null=True, unique=True)),
                ('title', models.CharField(max_length=255, null=True)),
                ('full_text', models.TextField()),
                ('news_hash', models.CharField(max_length=64)),
                ('publication_date', models.DateTimeField(null=True)),
                ('stock_mentions', models.JSONField(default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='StockCompany',
            fields=[
                ('symbol', models.CharField(max_length=20, primary_key=True, serialize=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='StockEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stock_name', models.CharField(blank=True, max_length=255, null=True)),
                ('mentioned_stock_name', models.CharField(max_length=255)),
                ('event_type', models.CharField(choices=[('FINANCIAL_REPORT', 'Financial Report'), ('DIVIDEND_ANNOUNCEMENT', 'Dividend Announcement'), ('STOCK_SPLIT', 'Stock Split'), ('MERGER_ACQUISITION', 'Merger or Acquisition'), ('MANAGEMENT_CHANGE', 'Management Change'), ('NEW_LISTING', 'New Listing'), ('DELISTING', 'Delisting'), ('REGULATORY_ACTION', 'Regulatory Action'), ('PRODUCT_LAUNCH', 'Major Product Launch'), ('PARTNERSHIP', 'Strategic Partnership'), ('LEGAL_ISSUE', 'Legal Issue or Lawsuit'), ('MARKET_EXPANSION', 'Market Expansion'), ('RESTRUCTURING', 'Company Restructuring'), ('EARNINGS_SURPRISE', 'Significant Earnings Surprise'), ('INSIDER_TRADING', 'Significant Insider Trading'), ('ANALYST_RATING_CHANGE', 'Major Analyst Rating Change'), ('OTHER', 'Other Important Event')], max_length=25)),
                ('importance', models.CharField(choices=[('CRITICAL', 'Critical'), ('IMPORTANT', 'Important'), ('REGULAR', 'Regular')], default='REGULAR', max_length=10)),
                ('description', models.TextField()),
                ('sentiment', models.CharField(blank=True, choices=[('VP', 'Very Positive'), ('P', 'Positive'), ('SP', 'Slightly Positive'), ('N', 'Neutral'), ('SN', 'Slightly Negative'), ('NG', 'Negative'), ('VN', 'Very Negative')], max_length=2, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events_old', to='news_analyzer.newsarticle')),
                ('stock_symbol', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='events', to='news_analyzer.stockcompany')),
            ],
        ),
        migrations.CreateModel(
            name='StockName',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('name_type', models.CharField(blank=True, max_length=10, null=True)),
                ('stock_symbol', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='news_analyzer.stockcompany')),
            ],
        ),
    ]
