# Generated by Django 5.2 on 2025-04-26 22:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NewsArticle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField(null=True, unique=True)),
                ('title', models.CharField(max_length=255, null=True)),
                ('full_text', models.TextField()),
                ('news_hash', models.CharField(max_length=64)),
                ('publication_date', models.DateTimeField(null=True)),
                ('stock_mentions', models.JSONField(default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('analyzed', models.BooleanField(default=False)),
                ('analyzed_at', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='StockCompany',
            fields=[
                ('symbol', models.CharField(max_length=20, primary_key=True, serialize=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='NewsSentiment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stock_name', models.CharField(blank=True, max_length=255, null=True)),
                ('mentioned_stock_name', models.CharField(max_length=255)),
                ('importance', models.CharField(choices=[('CRITICAL', 'Critical'), ('IMPORTANT', 'Important'), ('REGULAR', 'Regular')], default='REGULAR', max_length=10)),
                ('summary', models.TextField()),
                ('sentiment', models.CharField(blank=True, choices=[('VP', 'Very Positive'), ('P', 'Positive'), ('SP', 'Slightly Positive'), ('N', 'Neutral'), ('SN', 'Slightly Negative'), ('NG', 'Negative'), ('VN', 'Very Negative')], max_length=2, null=True)),
                ('reason', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events_old', to='news_analyzer.newsarticle')),
                ('stock_symbol', models.ManyToManyField(blank=True, null=True, related_name='events', to='news_analyzer.stockcompany')),
            ],
        ),
        migrations.CreateModel(
            name='StockDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sector_id', models.CharField(blank=True, max_length=100, null=True)),
                ('market_id', models.CharField(blank=True, max_length=100, null=True)),
                ('initial_shares', models.BigIntegerField(blank=True, null=True)),
                ('total_stocks', models.BigIntegerField(blank=True, null=True)),
                ('first_trading', models.DateTimeField(blank=True, null=True)),
                ('is_delisted', models.BooleanField(default=False)),
                ('is_etf', models.BooleanField(default=False)),
                ('primary_category', models.CharField(blank=True, choices=[('LEADERSHIP', 'leadership'), ('GROWTH', 'growth'), ('DIVIDEND', 'dividend'), ('DEFENSIVE', 'defensive'), ('CYCLICAL', 'cyclical'), ('VALUE', 'value'), ('SPECULATIVE', 'speculative'), ('INVESTMENT', 'investment'), ('LOSING', 'losing')], max_length=20, null=True)),
                ('secondary_category', models.CharField(blank=True, choices=[('LEADERSHIP', 'leadership'), ('GROWTH', 'growth'), ('DIVIDEND', 'dividend'), ('DEFENSIVE', 'defensive'), ('CYCLICAL', 'cyclical'), ('VALUE', 'value'), ('SPECULATIVE', 'speculative'), ('INVESTMENT', 'investment'), ('LOSING', 'losing')], max_length=20, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('stock_symbol', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='stock_detail', to='news_analyzer.stockcompany')),
            ],
        ),
        migrations.CreateModel(
            name='StockName',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('name_type', models.CharField(blank=True, max_length=10, null=True)),
                ('stock_symbol', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='news_analyzer.stockcompany')),
            ],
        ),
    ]
